///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package xilinx_zc706_base_axi_vip_0_0_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_PROTOCOL           = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_INTERFACE_MODE     = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_ADDR_WIDTH         = 32;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_DATA_WIDTH         = 32;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_ID_WIDTH           = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_AWUSER_WIDTH       = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_ARUSER_WIDTH       = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_RUSER_WIDTH        = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_WUSER_WIDTH        = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_BUSER_WIDTH        = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_SUPPORTS_NARROW    = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_BURST          = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_LOCK           = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_CACHE          = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_REGION         = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_QOS            = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_PROT           = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_WSTRB          = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_BRESP          = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_RRESP          = 1;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_ACLKEN         = 0;
      parameter xilinx_zc706_base_axi_vip_0_0_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////
typedef axi_mst_agent #(xilinx_zc706_base_axi_vip_0_0_VIP_PROTOCOL, 
                        xilinx_zc706_base_axi_vip_0_0_VIP_ADDR_WIDTH,
                        xilinx_zc706_base_axi_vip_0_0_VIP_DATA_WIDTH,
                        xilinx_zc706_base_axi_vip_0_0_VIP_DATA_WIDTH,
                        xilinx_zc706_base_axi_vip_0_0_VIP_ID_WIDTH,
                        xilinx_zc706_base_axi_vip_0_0_VIP_ID_WIDTH,
                        xilinx_zc706_base_axi_vip_0_0_VIP_AWUSER_WIDTH, 
                        xilinx_zc706_base_axi_vip_0_0_VIP_WUSER_WIDTH, 
                        xilinx_zc706_base_axi_vip_0_0_VIP_BUSER_WIDTH, 
                        xilinx_zc706_base_axi_vip_0_0_VIP_ARUSER_WIDTH,
                        xilinx_zc706_base_axi_vip_0_0_VIP_RUSER_WIDTH, 
                        xilinx_zc706_base_axi_vip_0_0_VIP_SUPPORTS_NARROW, 
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_BURST,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_LOCK,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_CACHE,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_REGION,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_PROT,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_QOS,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_WSTRB,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_BRESP,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_RRESP,
                        xilinx_zc706_base_axi_vip_0_0_VIP_HAS_ARESETN) xilinx_zc706_base_axi_vip_0_0_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      xilinx_zc706_base_axi_vip_0_0_mst_t  xilinx_zc706_base_axi_vip_0_0_mst;
//      initial begin : START_xilinx_zc706_base_axi_vip_0_0_MASTER
//        xilinx_zc706_base_axi_vip_0_0_mst = new("xilinx_zc706_base_axi_vip_0_0_mst", `xilinx_zc706_base_axi_vip_0_0_PATH_TO_INTERFACE);
//        xilinx_zc706_base_axi_vip_0_0_mst.start_master();
//      end



endpackage : xilinx_zc706_base_axi_vip_0_0_pkg
