# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mdu/Desktop/first_proj/xilinx_zc706_base/vitis/matmul_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/xilinx_zc706_base/ip/xilinx_zc706_base_matmul_1_0/xilinx_zc706_base_matmul_1_0.xci
# IP: The module: 'xilinx_zc706_base_matmul_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdu/Desktop/first_proj/xilinx_zc706_base/vitis/matmul_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/xilinx_zc706_base/ip/xilinx_zc706_base_matmul_1_0/constraints/matmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zc706_base_matmul_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mdu/Desktop/first_proj/xilinx_zc706_base/vitis/matmul_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/xilinx_zc706_base/ip/xilinx_zc706_base_matmul_1_0/xilinx_zc706_base_matmul_1_0.xci
# IP: The module: 'xilinx_zc706_base_matmul_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mdu/Desktop/first_proj/xilinx_zc706_base/vitis/matmul_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/xilinx_zc706_base/ip/xilinx_zc706_base_matmul_1_0/constraints/matmul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xilinx_zc706_base_matmul_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
