# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/mdu/Desktop/first_proj/xilinx_zc706_base/vitis/matmul_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/output/xilinx_zc706_base_ooc_copy.xdc

# Block Designs: bd/xilinx_zc706_base/xilinx_zc706_base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base || ORIG_REF_NAME==xilinx_zc706_base} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_axi_intc_0_0/xilinx_zc706_base_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_axi_intc_0_0 || ORIG_REF_NAME==xilinx_zc706_base_axi_intc_0_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_axi_vip_0_0/xilinx_zc706_base_axi_vip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_axi_vip_0_0 || ORIG_REF_NAME==xilinx_zc706_base_axi_vip_0_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_clk_wiz_0_0/xilinx_zc706_base_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_clk_wiz_0_0 || ORIG_REF_NAME==xilinx_zc706_base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_interconnect_axifull_0/xilinx_zc706_base_interconnect_axifull_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_interconnect_axifull_0 || ORIG_REF_NAME==xilinx_zc706_base_interconnect_axifull_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_proc_sys_reset_100MHz_0/xilinx_zc706_base_proc_sys_reset_100MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_proc_sys_reset_100MHz_0 || ORIG_REF_NAME==xilinx_zc706_base_proc_sys_reset_100MHz_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_proc_sys_reset_142MHz_0/xilinx_zc706_base_proc_sys_reset_142MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_proc_sys_reset_142MHz_0 || ORIG_REF_NAME==xilinx_zc706_base_proc_sys_reset_142MHz_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_proc_sys_reset_166MHz_0/xilinx_zc706_base_proc_sys_reset_166MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_proc_sys_reset_166MHz_0 || ORIG_REF_NAME==xilinx_zc706_base_proc_sys_reset_166MHz_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_proc_sys_reset_200MHz_0/xilinx_zc706_base_proc_sys_reset_200MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_proc_sys_reset_200MHz_0 || ORIG_REF_NAME==xilinx_zc706_base_proc_sys_reset_200MHz_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_proc_sys_reset_41MHz_0/xilinx_zc706_base_proc_sys_reset_41MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_proc_sys_reset_41MHz_0 || ORIG_REF_NAME==xilinx_zc706_base_proc_sys_reset_41MHz_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_proc_sys_reset_50MHz_0/xilinx_zc706_base_proc_sys_reset_50MHz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_proc_sys_reset_50MHz_0 || ORIG_REF_NAME==xilinx_zc706_base_proc_sys_reset_50MHz_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_ps7_0/xilinx_zc706_base_ps7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_ps7_0 || ORIG_REF_NAME==xilinx_zc706_base_ps7_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_ps7_axi_periph_0/xilinx_zc706_base_ps7_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_ps7_axi_periph_0 || ORIG_REF_NAME==xilinx_zc706_base_ps7_axi_periph_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_xbar_0/xilinx_zc706_base_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_xbar_0 || ORIG_REF_NAME==xilinx_zc706_base_xbar_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_matmul_1_0/xilinx_zc706_base_matmul_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_matmul_1_0 || ORIG_REF_NAME==xilinx_zc706_base_matmul_1_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_axi_ic_ps7_M_AXI_GP1_0/xilinx_zc706_base_axi_ic_ps7_M_AXI_GP1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_axi_ic_ps7_M_AXI_GP1_0 || ORIG_REF_NAME==xilinx_zc706_base_axi_ic_ps7_M_AXI_GP1_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_axi_intc_0_intr_1_interrupt_concat_0/xilinx_zc706_base_axi_intc_0_intr_1_interrupt_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_axi_intc_0_intr_1_interrupt_concat_0 || ORIG_REF_NAME==xilinx_zc706_base_axi_intc_0_intr_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_irq_const_tieoff_0/xilinx_zc706_base_irq_const_tieoff_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_irq_const_tieoff_0 || ORIG_REF_NAME==xilinx_zc706_base_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_auto_us_0/xilinx_zc706_base_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_auto_us_0 || ORIG_REF_NAME==xilinx_zc706_base_auto_us_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_s01_regslice_0/xilinx_zc706_base_s01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_s01_regslice_0 || ORIG_REF_NAME==xilinx_zc706_base_s01_regslice_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_auto_us_df_0/xilinx_zc706_base_auto_us_df_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_auto_us_df_0 || ORIG_REF_NAME==xilinx_zc706_base_auto_us_df_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_s02_regslice_0/xilinx_zc706_base_s02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_s02_regslice_0 || ORIG_REF_NAME==xilinx_zc706_base_s02_regslice_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_auto_us_df_1/xilinx_zc706_base_auto_us_df_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_auto_us_df_1 || ORIG_REF_NAME==xilinx_zc706_base_auto_us_df_1} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_auto_pc_0/xilinx_zc706_base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_auto_pc_0 || ORIG_REF_NAME==xilinx_zc706_base_auto_pc_0} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_auto_pc_1/xilinx_zc706_base_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_auto_pc_1 || ORIG_REF_NAME==xilinx_zc706_base_auto_pc_1} -quiet] -quiet

# IP: bd/xilinx_zc706_base/ip/xilinx_zc706_base_auto_pc_2/xilinx_zc706_base_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_zc706_base_auto_pc_2 || ORIG_REF_NAME==xilinx_zc706_base_auto_pc_2} -quiet] -quiet

# XDC: /home/mdu/Desktop/first_proj/xilinx_zc706_base/vitis/matmul_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/xilinx_zc706_base/xilinx_zc706_base_ooc.xdc
